all: mem1_v2 mem1_v3 mem2_v2

mem1_v2: mem1_v2.c
	gcc -o mem1_v2 mem1_v2.c

mem1_v3: mem1_v3.c
	gcc -o mem1_v3 mem1_v3.c

mem2_v2: mem2_v2.c
	gcc -o mem2_v2 mem2_v2.c

clean:
	rm mem1_v2 mem1_v3 mem1_v2

