all: alarm2 alarm3 ejemplo_signal ejemplo_signal2 eventos eventos2 eventos3 signal_perdido signal_perdido2

alarm2: ejemplo_alarm2.c
	gcc -o alarm2 ejemplo_alarm2.c

alarm3: ejemplo_alarm3.c
	gcc -o alarm3 ejemplo_alarm3.c

ejemplo_signal: ejemplo_signal.c
	gcc -o ejemplo_signal ejemplo_signal.c

ejemplo_signal2: ejemplo_signal2.c
	gcc -o ejemplo_signal2 ejemplo_signal2.c

eventos: eventos.c
	gcc -o eventos eventos.c

eventos2: eventos2.c
	gcc -o eventos2 eventos2.c

eventos3: eventos3.c
	gcc -o eventos3 eventos3.c

signal_perdido: signal_perdido.c
	gcc -o signal_perdido signal_perdido.c

signal_perdido2: signal_perdido2.c
	gcc -o signal_perdido2 signal_perdido2.c

clean:
	rm alarm2 alarm3 ejemplo_signal ejemplo_signal2 eventos eventos2 eventos3 signal_perdido signal_perdido2
